{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8fcd43f9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"\\nAn exception is an event, which occurs during the execution of a program that disrupts the normal flow of \\nthe program's instructions.\\n\\nSyntax errors are mistakes in the source code, such as spelling and punctuation errors, incorrect labels,\\nand so on which cause an error message to be generated by the compiler And Whereas an Exception occurs at runtime \\n\""
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Q1\n",
    "'''\n",
    "An exception is an event, which occurs during the execution of a program that disrupts the normal flow of \n",
    "the program's instructions.\n",
    "\n",
    "Syntax errors are mistakes in the source code, such as spelling and punctuation errors, incorrect labels,\n",
    "and so on which cause an error message to be generated by the compiler And Whereas an Exception occurs at runtime \n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e2907d46",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q2\n",
    "'''\n",
    "When an exception is not handled, it results in an uncaught exception. In programming, exceptions are raised when an error or unexpected situation occurs during the execution of a program. If the exception is not caught and handled properly, the program will terminate abruptly, and the error message or stack trace will be displayed, \n",
    "which can be disruptive to the user and may lead to data loss or other unexpected behavior.\n",
    "\n",
    "'''\n",
    "#Example\n",
    "def divide_numbers(a, b):\n",
    "    result = a / b\n",
    "    return result\n",
    "\n",
    "try:\n",
    "    num1 = int(input(\"Enter the first number: \"))\n",
    "    num2 = int(input(\"Enter the second number: \"))\n",
    "    result = divide_numbers(num1, num2)\n",
    "    print(f\"The result of division is: {result}\")\n",
    "except ValueError:\n",
    "    print(\"Invalid input! Please enter valid integers.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "437e9189",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q3\n",
    "#a\n",
    "try:\n",
    "  print(\"Hello\")\n",
    "except:\n",
    "  print(\"Something went wrong\")\n",
    "else:\n",
    "  print(\"Nothing went wrong\")\n",
    "\n",
    "#b\n",
    "try:\n",
    "  print(x)\n",
    "except:\n",
    "  print(\"Something went wrong\")\n",
    "finally:\n",
    "  print(\"The 'try except' is finished\")\n",
    "\n",
    "#c\n",
    "\n",
    "x = -1\n",
    "\n",
    "if x < 0:\n",
    "  raise Exception(\"Sorry, no numbers below zero\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a6697c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q4\n",
    "''' \n",
    "Custom exceptions in Python are user-defined exceptions that allow developers to create their own specific exception classes to represent unique error scenarios in their programs. \n",
    "Python provides the ability to create custom exception classes by inheriting from the built-in \n",
    "Exception class or any of its subclasses.\n",
    "\n",
    "We need custom exceptions when we encounter specific error conditions in our code that are not adequately represented by the built-in exception classes.\n",
    "'''\n",
    "#Example\n",
    "\n",
    "class CustomError(Exception):\n",
    "    pass\n",
    "\n",
    "raise CustomError(\"Example of Custom Exceptions in Python\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e17e5bd5",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q5\n",
    "\n",
    "class InvalidInputError(Exception):\n",
    "    def __init__(self, message):\n",
    "        self.message = message\n",
    "\n",
    "    def __str__(self):\n",
    "        return f\"Invalid Input: {self.message}\"\n",
    "\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    if b == 0:\n",
    "        raise InvalidInputError(\"Cannot divide by zero.\")\n",
    "    return a / b\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    try:\n",
    "        num1 = int(input(\"Enter the first number: \"))\n",
    "        num2 = int(input(\"Enter the second number: \"))\n",
    "        result = divide_numbers(num1, num2)\n",
    "        print(f\"The result of division is: {result}\")\n",
    "    except ValueError:\n",
    "        print(\"Invalid input! Please enter valid integers.\")\n",
    "    except InvalidInputError as e:\n",
    "        print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7e152718",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
